### ISSUE TITLE
ReachState attribute maxSpeed 0.0 not recognized, but 0.1 is

### ISSUE THREAD

**Issue by inigmatus** [jrossignol/ContractConfigurator#341] opened 2015-11-14 04:57 UTC
Currently maxSpeed attribute appears to be ignored altogether in parameter ReachState.

maxSpeed 0.0 is not recognized but 0.1 is.

Code example:
http://forum.kerbalspaceprogram.com/threads/101604-1-0-5-Contract-Configurator-v1-8-0-2015-11-09?p=2294583&viewfull=1#post2294583

**Comment by jrossignol** [comment] 2015-11-14 17:52
Not a bug - you're using minSpeed when you should be using maxSpeed.  You can also look at situation=LANDED, but I think if you're rolling that'll still count as landed..

**Comment by inigmatus** [comment] 2015-11-14 19:13
Sorry my bad. This is a maxSpeed bug. it was late at night. hehe.  maxSpeed does not recognize 0.0 but does recognize 0.1 speed.

//Island related Contracts
//CONTENT:
//Fly over the island, Land on the island

CONTRACT_TYPE
{
	name = CharterIslandTestB
    title = Test 101 B to KSC Island
    group = Island
	agent = SSI Aerospace
   
    description = Scientists and engineers often head out to KSC Island to work on various projects, and tourists to KSC know the island as one of the best places to camp out and watch launches. Shuttlecraft Systems Inc. has been chartered by KSC to provide regular air service to KSC Island. We need you to fly out two passengers to KSC Island, and exchange them with two passengers waiting there for a return trip to KSC.
	
	notes = Fly two passengers to KSC Island, drop them off and exchange them for two waiting passengers on the island, and return to KSC.
	
	synopsis = Regular flights to KSC Island are in high demand. The pay is low, but at least it's steady.
    completedMessage = Flight Completed!

    minExpiry = 7.0
    maxExpiry = 7.0
	deadline = 0
	cancellable = true
	declinable = true
    autoAccept = false
	
	prestige = Trivial

   	targetBody = Kerbin

   	maxCompletions = 0
   	maxSimultaneous = 1

 	rewardScience = 50000.0
  	rewardReputation = 5.0
  	rewardFunds = 10000.0
 	failureReputation = 20.0
  	failureFunds = 20000.0
  	advanceFunds = 5000000.0
	weight = 1000.0


	PARAMETER
	{
		name = ReachState
		type = ReachState
		title = Land back at KSC runway Speed 0
		hideChildren = true
//		maxSpeed = 0.0
		disableOnStateChange = false
	}
	
	PARAMETER
	{
		name = RecoverVessel
		type = RecoverVessel
	}
}

**Comment by inigmatus** [comment] 2015-11-14 19:15
http://forum.kerbalspaceprogram.com/threads/101604-1-0-5-Contract-Configurator-v1-8-0-2015-11-09?p=2295616#post2295616

**Comment by jrossignol** [comment] 2015-11-14 20:19
It's possible that this is due to a floating point issue (ie. your speed in KSP is 0.000000123), but I'll verify.

**Comment by jrossignol** [comment] 2015-11-14 20:28
Confirmed - KSP reports the speed as stuff like "0.0010787727766586" when sitting on the launchpad.    I'll still treat this as a bug and add in some code to round it.

**Comment by inigmatus** [comment] 2015-11-14 20:29
awesome. thanks. workaround for now is to use 0.1 for maxSpeed. thanks for your awesome help with this mod.

**Comment by jrossignol** [comment] 2015-11-14 20:35
Fixed for 1.8.1

**Closed by jrossignol** 2015-11-14 20:35 UTC
Labels: bug

**Comment by meyerweb** [comment] 2015-11-15 03:12
> You can also look at situation=LANDED, but I think if you're rolling that'll still count as landed..

Not that it matters to this particular report, but I can confirm that.  As soon as you touch down, you’re LANDED, regardless of speed, even if you immediately lose stability and crash.  This is why my spaceplane contracts all end with:

	situation = LANDED
	biome = Runway
	maxSpeed = 1
	PARAMETER
	{
		type = VesselNotDestroyed
	}

Good thing for me I accidentally picked a minSpeed value that avoided the floating-point errors!
