### ISSUE TITLE
BiomeTracker.OnLoad can sometimes throw an exception, preventing any ScenarioModule after it from being initialized

### ISSUE THREAD

**Issue by xEvilReeperx** [jrossignol/ContractConfigurator#258] opened 2015-07-11 20:37 UTC
I've got a user that reported this one. The stack trace should be informative enough:
```
[EXC 13:40:46.292] ArgumentException: 'Tekto' is not a valid CelestialBody.
	ContractConfigurator.ConfigNodeUtil.ParseCelestialBodyValue (System.String celestialName)
	ContractConfigurator.ConfigNodeUtil.ParseSingleValue[CelestialBody] (System.String key, System.String stringValue, Boolean allowExpression)
	ContractConfigurator.ConfigNodeUtil.ParseValue[CelestialBody] (.ConfigNode configNode, System.String key, Boolean allowExpression)
	ContractConfigurator.BiomeTracker.OnLoad (.ConfigNode node)
	ScenarioModule.Load (.ConfigNode node)
	ScenarioRunner.AddModule (.ConfigNode node)
	ProtoScenarioModule.Load (.ScenarioRunner host)
	ScenarioRunner+.MoveNext ()
```
In this user's case, it prevents ScienceAlertProfileManager (and some of your own -- teehee!) from running due to reasons you already know
```
ContractConfigurator.ExpressionParser.NumericValueExpressionParser`1[System.Double]: Unable to retrieve value for 'TouristCount' - PersistentDataStore is null.  This is likely caused by another ScenarioModule crashing, preventing others from loading.
```

[User's Post](http://forum.kerbalspaceprogram.com/threads/76793-1-0-4-ScienceAlert-1-8-8-Experiment-availability-feedback-%28July-5%29?p=2073318&viewfull=1#post2073318)
[User's Log](https://drive.google.com/file/d/0B58_NsfDEebxbTlFYkd0QWFzcEU/view?usp=sharing)

**Comment by CosmoBro** [comment] 2015-07-11 23:52
I've seen the post and the user report that he has removed OPM before of this. So that should be the problem because, Tekto is a OPM planet.

**Comment by SkyMarshal** [comment] 2015-07-12 01:18
I got this when using the Base Construction pack and the outer planet mod.  Upon reloading the save, without touching either, I got a similar exception and all my contract history was nuked.

**Comment by SkyMarshal** [comment] 2015-07-12 01:20
Correction: the tracking center is having a seizure.  Seems I have to reinstall now.  Sheesh.

**Comment by CosmoBro** [comment] 2015-07-12 01:32
mmm well my Base Construction pack uses a parameter system to support OPM and other planet packs. This look for all the planets, then make a list, after that I put a lot of parameters for orbit using that list (20 planets max). I look only for the celestials bodies that have surface so I dont know.
Also I only test it with OPM and RSS and no problem so far.

**Comment by SkyMarshal** [comment] 2015-07-12 02:13
The tracking center seemed unrelated, in hindsight:
```
[EXC 19:12:08.793] NullReferenceException: Object reference not set to an instance of an object
	Kopernicus.BarycenterUtils.onPlanetariumTargetChanged (.MapObject map)
	EventData`1[MapObject].Fire (.MapObject data)
	PlanetariumCamera.SetTarget (.MapObject tgt)
	Kopernicus.MapViewFixer.LateUpdate ()
```

**Comment by jrossignol** [comment] 2015-07-12 02:16
The tracking center might be related - depends on whether the NRE is due to a bad ScenarioModule.  Give me an hour or two and I should be able to get a fix done.

And the way it is supposed to behave is that it should silently remove planets that are invalidated from uninstalling planet packs.  At least, that's the theory. :wink:

**Comment by jrossignol** [comment] 2015-07-12 02:24
Okay, @SkyMarshal, give the pre-release dll [here](https://github.com/jrossignol/ContractConfigurator/blob/master/GameData/ContractConfigurator/ContractConfigurator.dll?raw=true) a shot.  If the issue is due to the same issue as was reported originally, it should resolve it in your save.  If not, then post the entire KSP.log and I'll take a closer look.

**Comment by jrossignol** [comment] 2015-07-12 02:24
Closing as fixed - will re-open if necessary.

**Closed by jrossignol** 2015-07-12 02:24 UTC
Labels: bug

**Comment by SkyMarshal** [comment] 2015-07-12 05:23
I'll test it in the morning.  Thanks for the quick work!
