### ISSUE TITLE
Failed to create Base Contract

### ISSUE THREAD

**Issue by dakakeisalie** [jrossignol/ContractConfigurator#349] opened 2015-11-20 06:10 UTC
Exception occured while attempt to generate contract of type 'BaseCreate':
System.InvalidOperationException: Operation is not valid due to the current state of the object
  at System.Linq.Enumerable.First[CelestialBody] (IEnumerable`1 source) [0x00000] in <filename unknown>:0 
  at ContractConfigurator.Behaviour.WaypointGenerator.Initialize () [0x00000] in <filename unknown>:0 
  at ContractConfigurator.Behaviour.WaypointGenerator..ctor (ContractConfigurator.Behaviour.WaypointGenerator orig, ContractConfigurator.ConfiguredContract contract) [0x00000] in <filename unknown>:0 
  at ContractConfigurator.Behaviour.WaypointGeneratorFactory.Generate (ContractConfigurator.ConfiguredContract contract) [0x00000] in <filename unknown>:0 
  at ContractConfigurator.BehaviourFactory.GenerateBehaviours (ContractConfigurator.ConfiguredContract contract, System.Collections.Generic.List`1 behaviourNodes) [0x00000] in <filename unknown>:0 
  at ContractConfigurator.ContractType.GenerateBehaviours (ContractConfigurator.ConfiguredContract contract) [0x00000] in <filename unknown>:0 
  at ContractConfigurator.ConfiguredContract.Initialize (ContractConfigurator.ContractType contractType) [0x00000] in <filename unknown>:0

**Comment by jrossignol** [comment] 2015-11-20 06:13
Although the error handling here needs to be cleaned up a bit, this could be a contract pack issue.  Do you know which Contract Pack BaseCreate is from?  I'm not familiar with it.  If you're unsure, then a list of contract packs you have installed would help me here.

**Comment by jrossignol** [comment] 2015-11-20 06:13
Also do you have RSS installed?  Or any planet packs?  Have you tried out planet packs, and then uninstalled them?  Those could all affect this one.

**Comment by dakakeisalie** [comment] 2015-11-20 06:26
Yeah it is CosmoBro's Base Construction. I just realized it is only 1.0.4 still. Probably some issue with that.
I haven't had any planets installed for a while, and this save certainly never had any.

**Comment by dakakeisalie** [comment] 2015-11-20 06:29
If it is of any use to you, I did the first contract to land a rover at a suitable site for a new Base on the Mun. I landed a later mission next to it for funsies, where I put Jeb behind the wheel. Unsurprisingly, I crashed in the low gravity. When I quickloaded (Quicksaved just before Jeb got in) an exception was thrown. I quit out of the game and reloaded, and the exception was thrown again. This second one was the one I posted here.

**Comment by severedsolo** [comment] 2015-11-20 06:58
The problem is 99% certainly with the pack itself. There are half a dozen validation errors. I fixed them a while ago and sent cosmo a pull request, but he's never responded.

**Comment by jrossignol** [comment] 2015-11-20 23:33
Well, I don't want to spend a ton of time supporting a questionable contract pack, but I suspect I see the problem.  Trying out a change, if you like you can test out the dev version to see if it fixes the issue:
https://github.com/jrossignol/ContractConfigurator/blob/master/GameData/ContractConfigurator/ContractConfigurator.dll?raw=true

Closing under the assumption that everything's fixed.

**Closed by jrossignol** 2015-11-20 23:33 UTC
Labels: bug

**Comment by dakakeisalie** [comment] 2015-11-21 00:48
Thanks for the dev build. I no longer get the exception thrown when I launch KSP, and I now get the "base construct" contract in the menu. "Land a base on  near your rover" (note the double space between on and near). I am assuming when I crashed my rover a bug in the base contract pack forgot where the rover was even though I quickloaded... I appreciate your quick response.

**Comment by CosmoBro** [comment] 2015-12-27 20:34
You can make an issue on [Base Construction](https://github.com/CosmoBro/BaseConstruction) for any problem with my pack I'll check it out when i have time
