### ISSUE TITLE
Erratic refreshing of missions on mission control screen

### ISSUE THREAD

**Issue by Spheniscine** [jrossignol/ContractConfigurator#613] opened 2017-01-04 16:21 UTC
Missions often refresh erratically when I'm on the mission control screen; some CC offered contracts are withdrawn, changed, or generated during these refreshes. This makes it difficult sometimes to accept something before getting the chance to read them.

A secondary effect is that whenever this happens, any contract (whether CC or stock) you're currently reading at the time, even accepted or completed ones, will be deselected, forcing you to select them again.

**Comment by HellDuke** [comment] 2017-02-07 12:06
I have clearly noticed this with 2 packs: Bases and Stations as well as Field research.

Bases and Stations example: I keep getting launch new Minmus and Mun space station contracts offered and pulled at random, most often appearing for only a few seconds. If a contract is accepted it stays. If using debug menu I disable check if target is Sun, I get contracts for new stations for Sun, Mun and Minmus but all of them remain stable as far as I can see.

Field research: Climate and Geology study contracts same as above but with "Must have valid experiment to run" disabled they will stay stable once offered.

**Comment by Leftyist** [comment] 2017-02-09 20:34
Just wanted to chime in and add that I am also getting this issue with the Bases and Stations contract pack. Makes it near impossible to actually take any of the contracts without just blindly accepting whatever you can see.

**Comment by severedsolo** [comment] 2017-03-05 09:28
Drysle on the forums has done some additional research into this see here:

http://forum.kerbalspaceprogram.com/index.php?/topic/91625-12x-contract-configurator-v1222-2016-12-16/&do=findComment&comment=2976111

Essentially it seems the issue is that when a DATA node is held at group level, and randomly generated (like my random rolls) - when CC rerolls the DATA node, it's updating them for offered contracts too, so the requirement can fail again. Offered contracts should not re-evaluate their requirements.

**Comment by jrossignol** [comment] 2017-06-11 15:29
There was a problem with REQUIREMENT nodes not being saved to contracts, which was causing it to look to the contract type instead (which means a re-roll could cause stuff already offered to change.  This *should* be fixed by the next release.

**Closed by jrossignol** 2017-06-11 15:29 UTC
Labels: bug

**Comment by TicTac-93** [comment] 2019-02-01 13:19
@jrossignol I'd like to request that this be re-opened, I can confirm it's present in the 1.27.1 release.  Same behavior of contracts appearing and disappearing as if they're being re-rolled after creation, and only Bases and Stations appears affected - I also have Tourism Plus and Clever Sats contract packs installed.
