### ISSUE TITLE
Contract Configurator + FAR incompatibility

### ISSUE THREAD

**Issue by RagingGamer** [jrossignol/ContractConfigurator#624] opened 2017-04-08 22:15 UTC
(Using the dev version of FAR)
One or the other causes the menus/buildings to be un-clickable. Or rather, clicking them accomplishes nothing.

On a vanilla KSP folder, with just these two mods installed, the problem occurs.

A video of exactly what's going on. (Tried GIF but was too low quality to see what was going on)
https://youtu.be/TRlAGJSuFhQ

I ran multiple tests.
Once with both
Once with FAR+MFI
Once with CC+MFI
Once with CC
Once with CC + FAR(no MFI)

Any combination that includes FAR itself and CC causes the bug.

EDIT: 
Realized I should provide the KSP.log.

Full log: https://www.dropbox.com/s/l7xgavvc8yyp3hs/KSP.log?dl=0

**Comment by theonegalen** [comment] 2017-04-20 23:33
@jrossignol, Ferram says it's on your end and he suspects you compiled in .NET 4.0 instead of 3.5

**Comment by jrossignol** [comment] 2017-04-20 23:58
It's doubtful that it was compiled with 4.0 if you're using the official
version.  I'd need to see the log file of the error in question to say for
sure though.

**Comment by jrossignol** [comment] 2017-05-30 04:27
This was due to the way Contract Configurator built its dynamic options menu (it broke toolbar code).  However, this was changed later, so if you update to a more recent version of Contract Configurator this should work for you.

Closing this issue, please re-open it if you can reproduce in Contract Configurator 1.22.2

**Closed by jrossignol** 2017-05-30 04:27 UTC
