### ISSUE TITLE
Null reference recovering

### ISSUE THREAD

**Issue by tomforwood** [jrossignol/ContractConfigurator#517] opened 2016-05-20 06:44 UTC
I just got an error from Contract configurator
```
Exception occured while saving ScenarioModule 'ContractVesselTracker':
System.NullReferenceException: Object reference not set to an instance of an object
  at ContractConfigurator.Extensions+<>c__DisplayClass5_1.<GetHashes>b__1 (.ProtoPartSnapshot childPart) [0x00000] in <filename unknown>:0 
  at System.Linq.Enumerable+<CreateWhereIterator>c__Iterator1D`1[ProtoPartSnapshot].MoveNext () [0x00000] in <filename unknown>:0 
  at System.Linq.Enumerable.First[ProtoPartSnapshot] (IEnumerable`1 source, System.Func`2 predicate, Fallback fallback) [0x00000] in <filename unknown>:0 
  at System.Linq.Enumerable.FirstOrDefault[ProtoPartSnapshot] (IEnumerable`1 source) [0x00000] in <filename unknown>:0 
  at ContractConfigurator.Extensions+<GetHashes>d__5.MoveNext () [0x00000] in <filename unknown>:0 
  at System.Linq.Enumerable.Contains[UInt32] (IEnumerable`1 source, UInt32 value, IEqualityComparer`1 comparer) [0x00000] in <filename unknown>:0 
  at System.Linq.Enumerable.Contains[UInt32] (IEnumerable`1 source, UInt32 value) [0x00000] in <filename unknown>:0 
  at ContractConfigurator.ContractVesselTracker+<>c__DisplayClass14_0.<OnSave>b__1 (.Vessel v) [0x00000] in <filename unknown>:0 
  at System.Collections.Generic.List`1[Vessel].GetIndex (Int32 startIndex, Int32 count, System.Predicate`1 match) [0x00000] in <filename unknown>:0 
  at System.Collections.Generic.List`1[Vessel].Find (System.Predicate`1 match) [0x00000] in <filename unknown>:0 
  at ContractConfigurator.ContractVesselTracker.OnSave (.ConfigNode node) [0x00000] in <filename unknown>:0 `
 It was after hitting recover on a submarine contract that I think came from tourism plus.
```
I hit ignore and the contract has been completed and I haven't noticed any ill effects yet

**Comment by jrossignol** [comment] 2016-05-21 14:50
Duplicate of #509

**Closed by jrossignol** 2016-05-21 14:50 UTC
Labels: duplicate
